// Stage 4B: the secret modes. GENERATED by a private script (never published). Only encrypted data lives here: for each mode an AES-GCM blob,
// its random salt and iv (base64), and the PBKDF2 round count. The key comes from the typed phrase, so nothing readable about the modes is stored
// (see js/theme.js for the design and what a determined person could still learn). Do not edit by hand.
export const SECRET = { n: 600000, modes: [
  { salt: 'OTga0utoxItD2Fwf9HEOaQ==', iv: 'qO+EQEOnftsrfSVp', data: 'N/f4U29KJxq58xYb62dPKdYnjaytSayPqJNrBiDHa3P2MX/QUoqOoV2WimFP1oQ+hgXOIwJ9DuT8ugUUIg5IJHyJgNIiV4ST3rQuWZTU7vFGWtT/HiB20mh6OQ/n3IytkTfVKu5d59XaE5T5GxFzp1Hmx7bzZB1ML7JF0lOnJXyuXNra7Aoh+T10g4weaJ9X7ySad3ZVBqr7RDNmlRyZVbKEranxsW0OZQARisMgR2cY+vOA/zju3T35IMsCho8f3qosxhq9D7ir0toNPKXNBpSFuAo+3F8KRMtpgPw6J3G1Eu7XGTluCJXB/NUJQtmNKmzS6SxKh40gECIN/BneqjSQXLo=' },
  { salt: 'gRz6xliqlrUUsCa6bqA3vw==', iv: '69jciFGoZKnthxgb', data: 'X+/oMQb2tIsoriwHBaTBXB8HcDTY6XVnCXVCV+eH4LQ0r0lyFzl3luaSoPN8KrIySJUHLeBaDm0u31T3/MQWlxnXSiF2ueFSite/iEBIZl/M9l6Cs++ULYcjMLdyqsoSCSLWJyZeH8AJ6W27Qht/i2FFrFLYUdRFbhPl6ylDB3dB/lKrMZEcKAeTSOmG1WpyCiuhlPnDYl71MeLyfO8naX9PDBLXJE+8rKJvK1GeyY1w8H+3xwqa0bBKCvJNIBFV048Vkmi4CkruN43UxOQzcXAKihU+Yl1p8wHQGQ==' },
] };
